name: Load JSON and Set Variables

on:
  push:
    branches:
      - main

jobs:
  load-json-and-set-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install jq
      run: sudo apt-get install jq

    
    - name: Display environment variables before
      run: env

    - name: Load JSON and set variables
      run: |
        string="$GITHUB_REPOSITORY"
        result="${string#vamshionrails/}"
        echo "$result"

        JSON_CONTENT=$(cat "$result.json")
        echo "$JSON_CONTENT"
        set_env_var() {
          echo "$1=$(echo "$JSON_CONTENT" | jq -r "$2")" >> $GITHUB_ENV
        }

        set_env_var "REPO_NAME" '.REPO_NAME'
        set_env_var "DESCRIPTION" '.DESCRIPTION'
        set_env_var "PRIVATE" '.PRIVATE'

        # Set nested variables
        set_env_var "TEST_NAME" '.TEST.TEST_NAME'

        # Set variables from TEST_ARRAY
        TEST_ARRAY_LENGTH=$(echo "$JSON_CONTENT" | jq -r '.TEST_ARRAY | length')
        for ((i=0; i<$TEST_ARRAY_LENGTH; i++)); do
          set_env_var "TEST_ARRAY_NAME_$i" ".TEST_ARRAY[$i].TEST_ARRAY_NAME"
        done
      env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_NAME: ${{ env.REPO_NAME }}
          DESCRIPTION: ${{ env.DESCRIPTION }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}

    - name: Display environment variables
      run: env

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.6.1'  # Specify the Helm version you want to use

    - name: Set up Helmfile
      run: |
        curl -fsSL -o /usr/local/bin/helmfile https://github.com/roboll/helmfile/releases/download/v0.140.0/helmfile_linux_amd64
        chmod +x /usr/local/bin/helmfile

    - name: Download Kubernetes Dashboard Helm Chart
      run: |
        helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
        helm repo update
        helm pull kubernetes-dashboard/kubernetes-dashboard --untar --destination "helmcharts/${{ steps.timestamp.outputs.timestamp }}"
        
    - name: Commit Helm Charts to GitHub
      run: |
        CHARTS_DIR="./helmcharts/${{ steps.timestamp.outputs.timestamp }}"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Update Helm charts ($(date +"%Y-%m-%d %H:%M:%S"))"
       git push https://$GITHUB_ACTOR:$YOUR_TOKEN@github.com/vamshionrails/your-repo.git HEAD:main
   
    
